### ISSUE TITLE
Proof of work?

### ISSUE THREAD

**Issue by jdom1824** [grisha/grisha.github.com#1]
Hello, i would like to know about how bitcoin processes  transactions. i'm reading about this topic, but i don't find anything technical. 

Do you recommend any reference? 

thanks for your attetion

**Comment by grisha** [comment]
I'd recommend the "Mastering Bitcoin" book: https://github.com/bitcoinbook/bitcoinbook

**Comment by jdom1824** [comment]
Hello, i'm reading book and have a question, I hope not to disturb. we know that in blockchain the bifurcation is a really, when this pass a fork is produced and the longest chain is maintained by consensus. My question is: ¿what happens with the transacction of the shortest chain? for example alice send a 0.001 bitcoin a bob, this transaction it is added to a block of the shortest chain and for consensus  it's going to be replaced.  ¿Alice would have to re-send 0.001 bitcoin a bob? ¿any reference on buffer?

Thanks for your time.

**Comment by grisha** [comment]
The chain consists of _blocks_, which contain many transactions. When the chain splits, the blocks on the shorter chain are not valid, it's as if they do not exist. When this happens all those transactions go back to the mempool, i.e. they are treated like new transactions, waiting to be included in a block. So the alice/bob transaction will eventually be included in a new valid block on the longer chain. The miners will do this, alice or bob do not need to do anything (other than wait a little longer). Hope this helps.

**Comment by jdom1824** [comment]
Hi Gregory,  after a brief  reading i conclude that bifurcation is very probable in bitcoin, my question in this chance is  why no work with la bifurcation? in distributed systems it's very common that there concurrent events. i'm trying to understand the UTXO, any reference that you can recommend me about this topic. 
regards.
